// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by `gen_gindices.rs`.

/// Returns the gindex of validators from BeaconState
#[inline(always)]
pub const fn validators_gindex() -> u64 {
    75u64
}
/// Returns the gindex of state_roots_base from BeaconState
#[inline(always)]
pub const fn state_roots_base_gindex() -> u64 {
    573440u64
}
/// Returns the gindex of historical_summaries_base from BeaconState
#[inline(always)]
pub const fn historical_summaries_base_gindex() -> u64 {
    3053453312u64
}
/// Returns the gindex of validator_balance_base from BeaconState
#[inline(always)]
pub const fn validator_balance_base_gindex() -> u64 {
    41781441855488u64
}
/// Returns the gindex of validator_withdrawal_credentials_base from BeaconState
#[inline(always)]
pub const fn validator_withdrawal_credentials_base_gindex() -> u64 {
    1319413953331201u64
}
/// Returns the gindex of validator_exit_epoch_base from BeaconState
#[inline(always)]
pub const fn validator_exit_epoch_base_gindex() -> u64 {
    1319413953331206u64
}
/// Returns the gindex of state_root from BeaconBlock
#[inline(always)]
pub const fn state_root_gindex() -> u64 {
    11u64
}
/// Returns the gindex of block_slot from BeaconBlock
#[inline(always)]
pub const fn block_slot_gindex() -> u64 {
    8u64
}
/// Returns the gindex of effective_balance from Validator i
#[inline(always)]
pub const fn effective_balance_gindex(i: u64) -> u64 {
    const CHUNK_OFFSET: u64 = 10u64 / 8u64;
    const WITHIN_CHUNK: u64 = 10u64 % 8u64;
    (2199023255552u64 + (i as u64)) * 8u64 * CHUNK_OFFSET + WITHIN_CHUNK
}
/// Returns the gindex of withdrawal_credentials from Validator i
#[inline(always)]
pub const fn withdrawal_credentials_gindex(i: u64) -> u64 {
    const CHUNK_OFFSET: u64 = 9u64 / 8u64;
    const WITHIN_CHUNK: u64 = 9u64 % 8u64;
    (2199023255552u64 + (i as u64)) * 8u64 * CHUNK_OFFSET + WITHIN_CHUNK
}
/// Returns the gindex of slashed from Validator i
#[inline(always)]
pub const fn slashed_gindex(i: u64) -> u64 {
    const CHUNK_OFFSET: u64 = 11u64 / 8u64;
    const WITHIN_CHUNK: u64 = 11u64 % 8u64;
    (2199023255552u64 + (i as u64)) * 8u64 * CHUNK_OFFSET + WITHIN_CHUNK
}
/// Returns the gindex of activation_epoch from Validator i
#[inline(always)]
pub const fn activation_epoch_gindex(i: u64) -> u64 {
    const CHUNK_OFFSET: u64 = 13u64 / 8u64;
    const WITHIN_CHUNK: u64 = 13u64 % 8u64;
    (2199023255552u64 + (i as u64)) * 8u64 * CHUNK_OFFSET + WITHIN_CHUNK
}
/// Returns the gindex of exit_epoch from Validator i
#[inline(always)]
pub const fn exit_epoch_gindex(i: u64) -> u64 {
    const CHUNK_OFFSET: u64 = 14u64 / 8u64;
    const WITHIN_CHUNK: u64 = 14u64 % 8u64;
    (2199023255552u64 + (i as u64)) * 8u64 * CHUNK_OFFSET + WITHIN_CHUNK
}
/// Returns the gindex for the length of a List<> type
#[inline(always)]
pub const fn length_gindex() -> u64 {
    3u64
}
